"""add degraded threshold

Revision ID: 0c9b38a99e06
Revises: ecba3de3c688
Create Date: 2026-09-01 07:20:37.508935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9b38a99e06'
down_revision: Union[str, Sequence[str], None] = 'ecba3de3c688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
def upgrade() -> None:
    op.add_column(
        "monitors",
        sa.Column(
            "degraded_threshold",
            sa.Integer(),
            nullable=False,
            server_default="2000",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'degraded_threshold')
    # ### end Alembic commands ###
