"""add monitor last checked

Revision ID: 128814898d26
Revises: bfb2cfd67160
Create Date: 2026-09-01 05:00:56.852606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128814898d26'
down_revision: Union[str, Sequence[str], None] = 'bfb2cfd67160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'last_checked_at')
    # ### end Alembic commands ###
