"""add recovery threshold

Revision ID: 38fbee6e05ca
Revises: 0c9b38a99e06
Create Date: 2026-09-01 07:38:14.360630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fbee6e05ca'
down_revision: Union[str, Sequence[str], None] = '0c9b38a99e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitors",
        sa.Column(
            "recovery_threshold",
            sa.Integer(),
            nullable=False,
            server_default="2",
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitors", "recovery_threshold")
    # ### end Alembic commands ###
