"""add consecutive failures

Revision ID: 822a1bb3ea03
Revises: 128814898d26
Create Date: 2026-09-01 06:25:03.435794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822a1bb3ea03'
down_revision: Union[str, Sequence[str], None] = '128814898d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'monitors',
        sa.Column(
            'consecutive_failures',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'consecutive_failures')
    # ### end Alembic commands ###
