"""add consecutive successes

Revision ID: ecba3de3c688
Revises: 822a1bb3ea03
Create Date: 2026-09-01 07:12:02.615507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecba3de3c688'
down_revision: Union[str, Sequence[str], None] = '822a1bb3ea03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'monitors',
        sa.Column(
            'consecutive_successes',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'consecutive_successes')
    # ### end Alembic commands ###
